name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests-per-env:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [test, py310test, py311test]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.5.1
        with:
          environments: ${{ matrix.environment }}
      - name: Test with Pixi
        run: |
          pixi run --environment ${{ matrix.environment }} test
